relation_mandatory_args = {
    "Accident": {"location", "trigger"},
    "CanceledRoute": {"location", "trigger"},
    "CanceledStop": {"location", "trigger"},
    "Delay": {"location", "trigger"},
    "Disaster": {"type", "location"},
    "Obstruction": {"location", "trigger"},
    "RailReplacementService": {"location", "trigger"},
    "TrafficJam": {"location", "trigger"},
    "Acquisition": {"buyer", "acquired"},
    "Insolvency": {"company", "trigger"},
    "Layoffs": {"company", "trigger"},
    "Merger": {"old", "new"},
    "OrganizationLeadership": {"organization", "person"},
    "SpinOff": {"parent", "child"},
    "Strike": {"company", "trigger"}
}

relation_mandatory_args_without_trigger = {
    "Accident": {"location"},
    "CanceledRoute": {"location"},
    "CanceledStop": {"location"},
    "Delay": {"location"},
    "Disaster": {"type", "location"},
    "Obstruction": {"location"},
    "RailReplacementService": {"location"},
    "TrafficJam": {"location"},
    "Acquisition": {"buyer", "acquired"},
    "Insolvency": {"company"},
    "Layoffs": {"company"},
    "Merger": {"old", "new"},
    "OrganizationLeadership": {"organization", "person"},
    "SpinOff": {"parent", "child"},
    "Strike": {"company"}
}
all_relation_types = list(relation_mandatory_args)

relation_arg_types = {
    'B-Obstruction-end_date': {'B-DATE', 'B-TIME'},
    'I-Obstruction-end_date': {'I-TIME', 'I-DATE'},
    'B-Obstruction-end_loc': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP', 'B-LOCATION_STREET'},
    'I-Obstruction-end_loc': {'I-LOCATION_STOP', 'I-LOCATION_CITY', 'I-LOCATION', 'I-LOCATION_STREET'},
    'B-Obstruction-start_loc': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP', 'B-LOCATION_STREET'},
    'I-Obstruction-start_loc': {'I-LOCATION_STOP', 'I-LOCATION_CITY', 'I-LOCATION', 'I-LOCATION_STREET'},
    'B-Obstruction-location': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STREET', 'B-LOCATION_ROUTE'},
    'I-Obstruction-location': {'I-LOCATION_ROUTE', 'I-LOCATION_STREET', 'I-LOCATION', 'I-LOCATION_CITY'},
    'B-Obstruction-trigger': {'B-TRIGGER'},
    'I-Obstruction-trigger': {'I-TRIGGER'},
    'B-Accident-end_loc': {'B-LOCATION', 'B-LOCATION_STREET'},
    'I-Accident-end_loc': {'I-LOCATION_STREET', 'I-LOCATION'},
    'B-Accident-start_loc': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STREET'},
    'I-Accident-start_loc': {'I-LOCATION_CITY', 'I-LOCATION_STREET', 'I-LOCATION'},
    'B-Accident-location': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STREET'},
    'I-Accident-location': {'I-LOCATION_STREET', 'I-LOCATION_CITY', 'I-LOCATION'},
    'B-Accident-trigger': {'B-DISASTER_TYPE', 'B-TRIGGER'}, 'I-Accident-trigger': {'I-TRIGGER', 'I-DISASTER_TYPE'},
    'B-Accident-direction': {'B-LOCATION', 'B-LOCATION_CITY'},
    'I-Accident-direction': {'I-LOCATION_CITY', 'I-LOCATION'}, 'B-Delay-delay': {'B-DURATION'},
    'I-Delay-delay': {'I-DURATION'}, 'B-Delay-start_loc': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP'},
    'I-Delay-start_loc': {'I-LOCATION_STOP', 'I-LOCATION_CITY', 'I-LOCATION'},
    'B-Delay-location': {'B-LOCATION', 'B-LOCATION_STOP', 'B-LOCATION_STREET', 'B-LOCATION_ROUTE'},
    'I-Delay-location': {'I-LOCATION_STOP', 'I-LOCATION_ROUTE', 'I-LOCATION_STREET', 'I-LOCATION'},
    'B-Delay-trigger': {'B-TRIGGER'}, 'I-Delay-trigger': {'I-TRIGGER'},
    'B-Delay-direction': {'B-LOCATION', 'B-LOCATION_STOP'}, 'I-Delay-direction': {'I-LOCATION_STOP', 'I-LOCATION'},
    'B-Disaster-location': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP', 'B-LOCATION_STREET'},
    'I-Disaster-location': {'I-LOCATION_STOP', 'I-LOCATION_STREET', 'I-LOCATION_CITY', 'I-LOCATION'},
    'B-Disaster-type': {'B-DISASTER_TYPE', 'B-TRIGGER'}, 'I-Disaster-type': {'I-TRIGGER', 'I-DISASTER_TYPE'},
    'B-CanceledStop-route': {'B-LOCATION_ROUTE'}, 'I-CanceledStop-route': {'I-LOCATION_ROUTE'},
    'B-CanceledStop-location': {'B-LOCATION_STOP'}, 'I-CanceledStop-location': {'I-LOCATION_STOP'},
    'B-CanceledStop-trigger': {'B-TRIGGER'}, 'I-CanceledStop-trigger': {'I-TRIGGER'},
    'B-OrganizationLeadership-person': {'B-PERSON', 'B-ORGANIZATION_COMPANY'},
    'I-OrganizationLeadership-person': {'I-PERSON', 'I-ORGANIZATION_COMPANY'},
    'B-OrganizationLeadership-organization': {'B-ORGANIZATION', 'B-ORGANIZATION_COMPANY'},
    'I-OrganizationLeadership-organization': {'I-ORGANIZATION_COMPANY', 'I-ORGANIZATION'},
    'B-OrganizationLeadership-position': {'B-ORG_POSITION'}, 'I-OrganizationLeadership-position': {'I-ORG_POSITION'},
    'B-OrganizationLeadership-from': {'B-DATE', 'B-TIME'},
    'I-OrganizationLeadership-from': {'B-DATE', 'B-TIME'},
    'B-OrganizationLeadership-trigger': {'B-TRIGGER'},
    'I-OrganizationLeadership-trigger': {'I-TRIGGER'},
    'B-TrafficJam-end_loc': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STREET'},
    'B-TrafficJam-start_date': {'B-DATE', 'B-TIME'},
    'I-TrafficJam-start_date': {'I-DATE', 'I-TIME'},
    'B-TrafficJam-end_date': {'B-DATE', 'B-TIME'},
    'I-TrafficJam-end_date': {'I-DATE', 'I-TIME'},
    'I-TrafficJam-end_loc': {'I-LOCATION_CITY', 'I-LOCATION_STREET', 'I-LOCATION'},
    'B-TrafficJam-start_loc': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP', 'B-LOCATION_STREET'},
    'I-TrafficJam-start_loc': {'I-LOCATION_STOP', 'I-LOCATION_CITY', 'I-LOCATION', 'I-LOCATION_STREET'},
    'B-TrafficJam-jam_length': {'B-DISTANCE'}, 'I-TrafficJam-jam_length': {'I-DISTANCE'},
    'B-TrafficJam-location': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STREET', 'B-LOCATION_ROUTE'},
    'I-TrafficJam-location': {'I-LOCATION_CITY', 'I-LOCATION_STREET', 'I-LOCATION', 'I-LOCATION_ROUTE'},
    'B-TrafficJam-trigger': {'B-TRIGGER'}, 'I-TrafficJam-trigger': {'I-TRIGGER'},
    'B-TrafficJam-direction': {'B-LOCATION', 'B-LOCATION_CITY'},
    'I-TrafficJam-direction': {'I-LOCATION_CITY', 'I-LOCATION'}, 'B-TrafficJam-delay': {'B-DURATION'},
    'I-TrafficJam-delay': {'I-DURATION'}, 'B-TrafficJam-cause': {'B-TRIGGER'}, 'I-TrafficJam-cause': {'I-TRIGGER'},
    'B-Delay-end_loc': {'B-LOCATION', 'B-LOCATION_STOP'}, 'I-Delay-end_loc': {'I-LOCATION_STOP', 'I-LOCATION'},
    'B-Obstruction-delay': {'B-DURATION'}, 'I-Obstruction-delay': {'I-DURATION'},
    'B-Strike-company': {'B-ORGANIZATION', 'B-ORGANIZATION_COMPANY'},
    'I-Strike-company': {'I-ORGANIZATION', 'I-ORGANIZATION_COMPANY'}, 'B-Strike-trigger': {'B-TRIGGER'},
    'I-Strike-trigger': {'I-TRIGGER'}, 'B-Disaster-date': {'B-DATE'}, 'I-Disaster-date': {'I-DATE'},
    'B-Disaster-victims': {'B-NUMBER'}, 'I-Disaster-victims': {'I-NUMBER'}, 'B-Obstruction-cause': {'B-TRIGGER'},
    'I-Obstruction-cause': {'I-TRIGGER'}, 'B-Merger-old': {'B-ORGANIZATION', 'B-ORGANIZATION_COMPANY'},
    'I-Merger-old': {'I-ORGANIZATION', 'I-ORGANIZATION_COMPANY'}, 'B-Merger-trigger': {'B-TRIGGER'},
    'I-Merger-trigger': {'I-TRIGGER'},
    'B-Obstruction-direction': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP', 'B-LOCATION_STREET'},
    'I-Obstruction-direction': {'I-LOCATION_STOP', 'I-LOCATION_STREET', 'I-LOCATION_CITY', 'I-LOCATION'},
    'B-CanceledRoute-end_loc': {'B-LOCATION', 'B-LOCATION_STOP'},
    'I-CanceledRoute-end_loc': {'I-LOCATION_STOP', 'I-LOCATION'},
    'B-CanceledRoute-start_loc': {'B-LOCATION', 'B-LOCATION_STOP'},
    'I-CanceledRoute-start_loc': {'I-LOCATION_STOP', 'I-LOCATION'},
    'B-CanceledRoute-location': {'B-LOCATION_STOP', 'B-LOCATION_ROUTE'},
    'I-CanceledRoute-location': {'I-LOCATION_STOP', 'I-LOCATION_ROUTE'}, 'B-CanceledRoute-trigger': {'B-TRIGGER'},
    'I-CanceledRoute-trigger': {'I-TRIGGER'}, 'B-RailReplacementService-end_loc': {'B-LOCATION_STOP'},
    'I-RailReplacementService-end_loc': {'I-LOCATION_STOP'}, 'B-RailReplacementService-start_loc': {'B-LOCATION_STOP'},
    'I-RailReplacementService-start_loc': {'I-LOCATION_STOP'},
    'B-RailReplacementService-location': {'B-LOCATION', 'B-LOCATION_ROUTE'},
    'I-RailReplacementService-location': {'I-LOCATION_ROUTE', 'I-LOCATION'},
    'B-RailReplacementService-trigger': {'B-TRIGGER'}, 'I-RailReplacementService-trigger': {'I-TRIGGER'},
    'B-SpinOff-date': {'B-DATE'}, 'I-SpinOff-date': {'I-DATE'},
    'B-SpinOff-parent': {'B-ORGANIZATION', 'B-ORGANIZATION_COMPANY'},
    'I-SpinOff-parent': {'I-ORGANIZATION', 'I-ORGANIZATION_COMPANY'}, 'B-SpinOff-trigger': {'B-TRIGGER'},
    'I-SpinOff-trigger': {'I-TRIGGER'}, 'B-SpinOff-child': {'B-ORGANIZATION_COMPANY'},
    'I-SpinOff-child': {'I-ORGANIZATION_COMPANY'}, 'B-Insolvency-company': {'B-ORGANIZATION', 'B-ORGANIZATION_COMPANY'},
    'I-Insolvency-company': {'I-ORGANIZATION', 'I-ORGANIZATION_COMPANY'}, 'B-Insolvency-trigger': {'B-TRIGGER'},
    'I-Insolvency-trigger': {'I-TRIGGER'}, 'B-Delay-cause': {'B-TRIGGER'}, 'I-Delay-cause': {'I-TRIGGER'},
    'B-Layoffs-company': {'B-ORGANIZATION_COMPANY'}, 'I-Layoffs-company': {'I-ORGANIZATION_COMPANY'},
    'B-Layoffs-location': {'B-LOCATION', 'B-LOCATION_CITY'}, 'I-Layoffs-location': {'I-LOCATION_CITY', 'I-LOCATION'},
    'B-Layoffs-trigger': {'B-TRIGGER'}, 'I-Layoffs-trigger': {'I-TRIGGER'},
    'B-CanceledRoute-direction': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP'},
    'I-CanceledRoute-direction': {'I-LOCATION_STOP', 'I-LOCATION_CITY', 'I-LOCATION'},
    'B-Insolvency-location': {'B-LOCATION', 'B-LOCATION_CITY'},
    'I-Insolvency-location': {'I-LOCATION_CITY', 'I-LOCATION'}, 'B-Insolvency-date': {'B-DATE'},
    'I-Insolvency-date': {'I-DATE'}, 'B-RailReplacementService-end_date': {'B-DATE'},
    'I-RailReplacementService-end_date': {'I-DATE'}, 'B-RailReplacementService-start_date': {'B-DATE', 'B-TIME'},
    'I-RailReplacementService-start_date': {'I-TIME', 'I-DATE'}, 'B-Acquisition-trigger': {'B-TRIGGER'},
    'I-Acquisition-trigger': {'I-TRIGGER'}, 'B-Acquisition-acquired': {'B-ORGANIZATION_COMPANY'},
    'I-Acquisition-acquired': {'I-ORGANIZATION_COMPANY'},
    'B-Acquisition-buyer': {'B-ORGANIZATION', 'B-ORGANIZATION_COMPANY'},
    'I-Acquisition-buyer': {'I-ORGANIZATION', 'I-ORGANIZATION_COMPANY'},
    'B-Accident-start_date': {'B-DATE', 'B-TIME'},
    'I-Accident-start_date': {'I-TIME', 'I-DATE'},
    'B-Accident-cause': {'B-TRIGGER'},
    'I-Accident-cause': {'I-TRIGGER'},
    'B-Obstruction-start_date': {'B-DATE', 'B-TIME'},
    'I-Obstruction-start_date': {'I-TIME', 'I-DATE'},
    'B-RailReplacementService-cause': {'B-TRIGGER'},
    'I-RailReplacementService-cause': {'I-TRIGGER'},
    'B-CanceledRoute-start_date': {'B-DATE', 'B-TIME'},
    'I-CanceledRoute-start_date': {'I-TIME', 'I-DATE'},
    'B-Acquisition-price': {'B-NUMBER'},
    'I-Acquisition-price': {'I-NUMBER'},
    'B-Layoffs-num_laid_off': {'B-NUMBER'},
    'I-Layoffs-num_laid_off': {'I-NUMBER'},
    'B-Strike-date': {'B-DATE'}, 'I-Strike-date': {'I-DATE'},
    'B-Accident-end_date': {'B-DATE'},
    'I-Accident-end_date': {'I-DATE'}, 'B-Layoffs-date': {'B-DATE'}, 'I-Layoffs-date': {'I-DATE'},
    'B-Strike-location': {'B-LOCATION', 'B-LOCATION_CITY', 'B-LOCATION_STOP'},
    'I-Strike-location': {'I-LOCATION_STOP', 'I-LOCATION_CITY', 'I-LOCATION'},
    'B-Delay-start_date': {'B-DATE', 'B-TIME'}, 'I-Delay-start_date': {'I-TIME', 'I-DATE'},
    'B-Strike-union': {'B-ORGANIZATION'}, 'I-Strike-union': {'I-ORGANIZATION'}, 'B-Strike-num_striking': {'B-NUMBER'},
    'I-Strike-num_striking': {'I-NUMBER'}, 'B-CanceledStop-direction': {'B-LOCATION_STOP'},
    'I-CanceledStop-direction': {'I-LOCATION_STOP'}, 'B-CanceledStop-start_date': {'B-DATE', 'B-TIME'},
    'I-CanceledStop-start_date': {'I-TIME', 'I-DATE'}, 'B-CanceledRoute-end_date': {'B-DATE', 'B-TIME'},
    'I-CanceledRoute-end_date': {'I-TIME', 'I-DATE'}, 'B-Merger-new': {'B-ORGANIZATION', 'B-ORGANIZATION_COMPANY'},
    'I-Merger-new': {'I-ORGANIZATION', 'I-ORGANIZATION_COMPANY'}, 'B-CanceledRoute-cause': {'B-TRIGGER'},
    'I-CanceledRoute-cause': {'I-TRIGGER'}, 'B-RailReplacementService-direction': {'B-LOCATION_STOP'},
    'I-RailReplacementService-direction': {'I-LOCATION_STOP'}, 'B-Merger-date': {'B-DATE'}, 'I-Merger-date': {'I-DATE'},
    'B-Acquisition-seller': {'B-ORGANIZATION_COMPANY'}, 'I-Acquisition-seller': {'I-ORGANIZATION_COMPANY'},
    'B-Disaster-trigger': {'B-TRIGGER'}, 'I-Disaster-trigger': {'I-TRIGGER'},
    'B-Disaster-damage_costs': {'B-NUMBER'},
    'I-Disaster-damage_costs': {'I-NUMBER'},
    'B-Strike-striker': {'B-PERSON'},
    'I-Strike-striker': {'I-PERSON'}, 'B-Accident-delay': {'B-DURATION'}, 'I-Accident-delay': {'I-DURATION'},
    'B-CanceledStop-end_date': {'B-DATE'}, 'I-CanceledStop-end_date': {'I-DATE'}, 'B-Acquisition-date': {'B-DATE'},
    'I-Acquisition-date': {'I-DATE'}, 'B-CanceledStop-cause': {'B-TRIGGER'}, 'I-CanceledStop-cause': {'I-TRIGGER'},
    'B-Delay-end_date': {'B-DATE'}, 'I-Delay-end_date': {'I-DATE'}}

replacable_args = {
    'Obstruction-location': {'TrafficJam-location', 'RailReplacementService-location', 'Disaster-location',
                             'Accident-location', 'Obstruction-location', 'Delay-location'},
    'Delay-location': {'CanceledRoute-location', 'Obstruction-location', 'Delay-location'},
    'Accident-location': {'Accident-location', 'Obstruction-location', 'TrafficJam-location'},
    'TrafficJam-location': {'Accident-location', 'Obstruction-location', 'TrafficJam-location'},
    'CanceledRoute-location': {'CanceledRoute-location', 'RailReplacementService-location', 'Delay-location'},
    'RailReplacementService-location': {'CanceledRoute-location', 'Obstruction-location',
                                        'RailReplacementService-location'},
    'Disaster-location': {'Disaster-location', 'Obstruction-location', 'CanceledStop-location'},
    'CanceledRoute-trigger': {'CanceledRoute-trigger'},
    'RailReplacementService-trigger': {'RailReplacementService-trigger'},
    'OrganizationLeadership-organization': {'OrganizationLeadership-organization'},
    'Insolvency-trigger': {'Insolvency-trigger'}, 'Delay-trigger': {'Delay-trigger'},
    'Accident-trigger': {'Obstruction-trigger', 'Accident-trigger'},
    'Obstruction-trigger': {'Obstruction-trigger', 'Accident-trigger'}, 'Disaster-type': {'Disaster-type'},
    'Insolvency-company': {'Insolvency-company', 'Acquisition-acquired', 'Layoffs-company'},
    'Acquisition-acquired': {'Acquisition-acquired', 'Insolvency-company'},
    'Acquisition-buyer': {'Layoffs-company', 'Acquisition-buyer'},
    'Layoffs-company': {'Insolvency-company', 'Layoffs-company', 'Acquisition-buyer'},
    'Strike-trigger': {'Strike-trigger'}, 'CanceledStop-location': {'Disaster-location', 'CanceledStop-location'},
    'Layoffs-trigger': {'Layoffs-trigger'}}

entity_types = {'LOCATION_STOP', 'DISTANCE', 'ORGANIZATION', 'NUMBER', 'DATE', 'TRIGGER', 'LOCATION_ROUTE',
                'PERSON', 'LOCATION', 'TIME', 'LOCATION_STREET', 'ORGANIZATION_COMPANY', 'LOCATION_CITY',
                'DURATION', 'DISASTER_TYPE', 'ORG_POSITION'}

mandatory_entity_types = {'LOCATION_CITY', 'LOCATION_STREET', 'LOCATION_STOP', 'ORGANIZATION', 'PERSON',
                          'DISASTER_TYPE', 'LOCATION', 'TRIGGER', 'LOCATION_ROUTE', 'ORGANIZATION_COMPANY'}
