name: mare
channels:
  - pytorch
  - default
  - conda-forge
  - plotly
  - bokeh
dependencies:
  - allennlp-optuna=0.1.4
  - python=3.8
  - html2text=2020.1.16
  - pip=20.3.3
  - srsly=1.0.5
  - tqdm=4.56.0
  - pytorch=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=10.2.89
  - spacy=2.3.5
  - jupyter=1.0.0
  - matplotlib=3.3.3
  - seaborn=0.11.1
  - pathlib2=2.3.5
  - plotly=4.14.3
  - python-kaleido
  - fastavro=1.3.0
  - python-snappy=0.5.4
  - beautifulsoup4=4.9.3
  - click=7.1.2
  - mysqlclient=2.0.3
  - phantomjs
  - selenium
  - psutil
  - pip:
    - allennlp==1.2.0
    - allennlp-models==1.2.0
    - optuna-dashboard==0.2.2
    - streamlit==0.75.0
    - htbuilder==0.3.0
    - bokeh==1.4.0
    - flaky==3.7.0
    - mlflow==1.13.1